const BeautyData = [
  {
    id: 1,
    womenpic: "./assets/beautyimages/cosmetic.png",
    brandname: " INFINITY",
    picdetail: "Cosmetic",
    price: 1614,
    Category: "Cosmetics",
    quantity: 4,
  },
  {
    id: 2,
    womenpic: "./assets/beautyimages/lipstick.png",
    brandname: " INFINITY",
    picdetail: "Lipstick",
    price: 1614,
    Category: "Lipsticks",
    quantity: 4,
  },
  {
    id: 3,
    womenpic: "./assets/beautyimages/nailpolish.png",
    brandname: " INFINITY",
    picdetail: "Nail paint",
    price: 1614,
    Category: "Nail Paints",
    quantity: 4,
  },
  {
    id: 4,
    womenpic: "./assets/beautyimages/perfume.png",
    brandname: " INFINITY",
    picdetail: "Perfume",
    price: 1614,
    Category: "Perfumes",
    quantity: 4,
  },
  {
    id: 5,
    womenpic: "./assets/beautyimages/cosmetic2.png",
    brandname: " INFINITY",
    picdetail: "Cosmetic",
    price: 1614,
    Category: "Cosmetics",
    quantity: 4,
  },
  {
    id: 6,
    womenpic: "./assets/beautyimages/lipstick2.png",
    brandname: " INFINITY",
    picdetail: "Lipstick",
    price: 1614,
    Category: "Lipsticks",
    quantity: 4,
  },
  {
    id: 7,
    womenpic: "./assets/beautyimages/nailpolish.png",
    brandname: " INFINITY",
    picdetail: "Nail paint",
    price: 1614,
    Category: "Nail Paints",
    quantity: 4,
  },
  {
    id: 8,
    womenpic: "./assets/beautyimages/perfume2.png",
    brandname: " INFINITY",
    picdetail: "Perfume",
    price: 1614,
    Category: "Perfumes",
    quantity: 4,
  },
  {
    id: 9,
    womenpic: "./assets/beautyimages/cosmetic4.png",
    brandname: " INFINITY",
    picdetail: "Cosmetic",
    price: 1614,
    Category: "Cosmetics",
    quantity: 4,
  },
  {
    id: 10,
    womenpic: "./assets/beautyimages/lipstick3.png",
    brandname: " INFINITY",
    picdetail: "Lipstick",
    price: 1614,
    Category: "Lipsticks",
    quantity: 4,
  },
  {
    id: 11,
    womenpic: "./assets/beautyimages/nailpolish.png",
    brandname: " INFINITY",
    picdetail: "Nail paint",
    price: 1614,
    Category: "Nail Paints",
    quantity: 4,
  },
  {
    id: 12,
    womenpic: "./assets/beautyimages/perfume4.png",
    brandname: " INFINITY",
    picdetail: "Perfume",
    price: 1614,
    Category: "Perfumes",
    quantity: 4,
  },
  {
    id: 13,
    womenpic: "./assets/beautyimages/cosmetic4.png",
    brandname: " INFINITY",
    picdetail: "Cosmetic",
    price: 1614,
    Category: "Cosmetics",
    quantity: 4,
  },
  {
    id: 14,
    womenpic: "./assets/beautyimages/lipstick.png",
    brandname: " INFINITY",
    picdetail: "Lipstick",
    price: 1614,
    Category: "Lipsticks",
    quantity: 4,
  },
  {
    id: 15,
    womenpic: "./assets/beautyimages/nailpolish.png",
    brandname: " INFINITY",
    picdetail: "Nail paint",
    price: 1614,
    Category: "Nail Paints",
    quantity: 4,
  },
  {
    id: 16,
    womenpic: "./assets/beautyimages/perfume4.png",
    brandname: " INFINITY",
    picdetail: "Perfume",
    price: 1614,
    Category: "Perfumes",
    quantity: 4,
  },
];
export default BeautyData;
