const Data = [
    {
      id: 1,
      womenpic: "./assets/womenimages/all/women_jeans.png",
      brandname: " INFINITY",
      picdetail: "Cool Jeans",
      price: 1614,
      Category: "Jeans",
      quantity: 1,
    },
    {
      id: 2,
      womenpic: "./assets/womenimages/all/women_watch.png",
      brandname: " INFINITY",
      picdetail: "classic Watch",
      price: 1614,
      Category: "Watch",
      quantity: 5,
    },
    {
      id: 3,
      womenpic: "./assets/womenimages/all/women_shirt.png",
      brandname: " INFINITY",
      picdetail: "Trendy Shirt",
      price: 1614,
      Category: "Shirt",
      quantity: 1,
    },
    {
      id: 4,
      womenpic: "./assets/womenimages/all/women_footwear.png",
      brandname: " INFINITY",
      picdetail: "Sandles",
      price: 1614,
      Category: "Footwear",
      quantity: 2,
    },
    {
      id: 5,
      womenpic: "./assets/womenimages/all/women_tshirt.png",
      brandname: " INFINITY",
      picdetail: "Simple T-shirt",
      price: 1614,
      Category: "T-shirt",
      quantity: 6,
    },
    {
      id: 6,
      womenpic: "./assets/womenimages/all/women_saree.png",
      brandname: " INFINITY",
      picdetail: "Beutifull Saree",
      price: 1614,
      Category: "Saree",
      quantity: 2,
    },
  
    {
      id: 7,
      womenpic: "./assets/womenimages/all/women_jeans.png",
      brandname: " INFINITY",
      picdetail: "Cool Jeans",
      price: 1614,
      Category: "Jeans",
      quantity: 4,
    },
    {
      id: 8,
      womenpic: "./assets/womenimages/all/women_watch.png",
      brandname: " INFINITY",
      picdetail: "classic Watch",
      price: 1614,
      Category: "Watch",
      quantity: 3,
    },
    {
      id: 9,
      womenpic: "./assets/womenimages/all/women_shirt.png",
      brandname: " INFINITY",
      picdetail: "Trendy Shirt",
      price: 1614,
      Category: "Shirt",
      quantity: 3,
    },
    {
      id: 10,
      womenpic: "./assets/womenimages/all/women_footwear.png",
      brandname: " INFINITY",
      picdetail: "Sandles",
      price: 1614,
      Category: "Footwear",
      quantity: 2,
    },
    {
      id: 11,
      womenpic: "./assets/womenimages/all/women_tshirt.png",
      brandname: " INFINITY",
      picdetail: "Simple T-shirt",
      price: 1614,
      Category: "T-shirt",
      quantity: 1,
    },
    {
      id: 12,
      womenpic: "./assets/womenimages/all/women_saree.png",
      brandname: " INFINITY",
      picdetail: "Beutifull Saree",
      price: 1614,
      Category: "Saree",
      quantity: 4,
    },
  
    {
      id: 13,
      womenpic: "./assets/womenimages/all/women_jeans.png",
      brandname: " INFINITY",
      picdetail: "Cool Jeans",
      price: 1614,
      Category: "Jeans",
      quantity: 3,
    },
    {
      id: 14,
      womenpic: "./assets/womenimages/all/women_watch.png",
      brandname: " INFINITY",
      picdetail: "classic Watch",
      price: 1614,
      Category: "Watch",
      quantity: 2,
    },
    {
      id: 15,
      womenpic: "./assets/womenimages/all/women_shirt.png",
      brandname: " INFINITY",
      picdetail: "Trendy Shirt",
      price: 1614,
      Category: "Shirt",
      quantity: 2,
    },
    {
      id: 16,
      womenpic: "./assets/womenimages/all/women_footwear.png",
      brandname: " INFINITY",
      picdetail: "Sandles",
      price: 1614,
      Category: "Footwear",
      quantity: 2,
    },
    {
      id: 17,
      womenpic: "./assets/womenimages/all/women_tshirt.png",
      brandname: " INFINITY",
      picdetail: "Simple T-shirt",
      price: 1614,
      Category: "T-shirt",
      quantity: 1,
    },
    {
      id: 18,
      womenpic: "./assets/womenimages/all/women_saree.png",
      brandname: " INFINITY",
      picdetail: "Beutifull Saree",
      price: 1614,
      Category: "Saree",
      quantity: 1,
    },
  
    {
      id: 19,
      womenpic: "./assets/womenimages/all/women_jeans.png",
      brandname: " INFINITY",
      picdetail: "Cool Jeans",
      price: 1614,
      Category: "Jeans",
      quantity: 5,
    },
    {
      id: 20,
      womenpic: "./assets/womenimages/all/women_watch.png",
      brandname: " INFINITY",
      picdetail: "classic Watch",
      price: 1614,
      Category: "Watch",
      quantity: 1,
    },
    {
      id: 21,
      womenpic: "./assets/womenimages/all/women_shirt.png",
      brandname: " INFINITY",
      picdetail: "Trendy Shirt",
      price: 1614,
      Category: "Shirt",
      quantity: 2,
    },
    {
      id: 22,
      womenpic: "./assets/womenimages/all/women_footwear.png",
      brandname: " INFINITY",
      picdetail: "Sandles",
      price: 1614,
      Category: "Footwear",
      quantity: 1,
    },
    {
      id: 23,
      womenpic: "./assets/womenimages/all/women_tshirt.png",
      brandname: " INFINITY",
      picdetail: "Simple T-shirt",
      price: 1614,
      Category: "T-shirt",
      quantity: 1,
    },
    {
      id: 24,
      womenpic: "./assets/womenimages/all/women_saree.png",
      brandname: " INFINITY",
      picdetail: "Beutifull Saree",
      price: 1614,
      Category: "Saree",
      quantity: 2,
    },
  ];
  
  export default Data;